name = "Easy Docs"
license = "MIT"
description = "Easy, all-in-one beautiful documentation website including a customizable homepage and blog. Super fast, empowering you to focus on your content."

homepage = "https://github.com/hugoflow/hugo-theme-doc"
demosite = "https://hugofus.web.app/"

tags = ["landing", "docs", "blog", "responsive", "minimal", "light", "dark", "multilingual", "dark mode", "tailwind", "company", "gallery"]
features = ["secure", "fast", "search", "dark mode", "widgets"]

# If the theme has a single author
[author]
  name = "hugo flow"
  homepage = "https://hugofus.web.app"
